language: ruby
cache: bundler
matrix:
 include:
  - rvm: 2.3
  - rvm: 2.4
  - rvm: 2.5
  - rvm: 2.6
  - gemfile: test/gemfiles/with_rinku.gemfile
    rvm: 2.6

branches:
  only:
    - master

before_install:
  - gem update --system
  - gem install kramdown
  - 'gem install rake && rake bootstrap'

notifications:
  email: false
